name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Setup git
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Build changelog
        id: build_changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export CHANGELOG=$(gh api /repos/{owner}/{repo}/releases/generate-notes -f tag_name="${GITHUB_REF#refs/tags/}" --jg ".body")
          echo "CHANGELOG=$CHANGELOG" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make release tag="${GITHUB_REF#refs/tags/}" changelog="${{ env.CHANGELOG }}" repo=asanchezr/PSP

      - name: Post notification in MS Teams
        run: |
          echo "Teams notification sent..."
